### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by DetectiveSquirrel** [eklypss/PUBGSharp#12]
How do i compile the wrapper, using VS 2015 never ran into the problem before.
`PUBGSharp\PUBGSharp.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\tuba\Documents\GitHub\PUBGSharp\PUBGSharp\PUBGSharp.csproj`

**Comment by eklypss** [comment]
I think you need VS 2017, possibly with .NET Core tooling (or perhaps the SDK) installed as well. Not 100% sure though.

**Comment by DetectiveSquirrel** [comment]
Installed VS '17 + most options in it and seems to have fixed the problem, cheers.
