### ISSUE TITLE
PUBGStatsClient.GetPlayerStatsAsync doesn't work

### ISSUE THREAD

**Issue by Stanley1551** [eklypss/PUBGSharp#24]
With the given example, I constantly get an exception with a message that claims the player doesn't exist.
API key and player name (tried with several player names) are all valid.

**Comment by EolmY** [comment]
Post your Code. The Examples work fine for me.

**Comment by Stanley1551** [comment]
Sorry for disturbing, it is working now.
Later when I posted this, I looked up my stats on pubgtracker website, and found out that the PUBG Stat servers are down. This might have been the case, 'coz now I get the response.
