### ISSUE TITLE
Cant get data if pubg servers are down.

### ISSUE THREAD

**Issue by CGKajm** [eklypss/PUBGSharp#25]
Hey is there a way to get the last non updated data? I see its viable as I saw at other people program, but  I dont know how to get it here, I see when I have GetPlayerAsync and servers are down I get an exception and I cant find a way to get the older data from their database

**Comment by CGKajm** [comment]
When I changed your string request to  string request = $"https://api.pubgtracker.com/v2/profile/pc/{playerName}"; I got it working

**Comment by Stanley1551** [comment]
Great workaround, a decent fallback mechanism could be implemented this way.
