### ISSUE TITLE
Needs update for 2018 release season(s)

### ISSUE THREAD

**Issue by AliStarr** [eklypss/PUBGSharp#26]
Currently there is no option in the Regions enum for the newest season or future proofing for the seasons as they come.

**Comment by CGKajm** [comment]
Just add it yourself, it's one line of code

**Comment by Stanley1551** [comment]
Yes, an update would be great. Looking forward for it!

**Comment by CGKajm** [comment]
Just have a look at the PUBGTracker API for the new season key (new season is: 2018-01 and the following seasons will probably follow the same pattern) Just add another `public const string` and add the value of the new season so now it will be `public const string Season1= "2018-01";` 

Probably the next season will follow the same pattern AKA 2018-02,03,04 ....
