### ISSUE TITLE
Failed to deserialize data (Weapons Acquired)

### ISSUE THREAD

**Issue by max-xface** [eklypss/PUBGSharp#4]
Failed to deserialize data: Error converting value "Weapons Acquired" to type 'PUBGSharp.Stat'. Path 'Stats[0].Stats[33].label', line 1, position 8862.

**Comment by eklypss** [comment]
Fixed in 1.1.3, I'll change it so it doesn't break when new stats are added soon.

**Comment by max-xface** [comment]
Thank you! After update it is working
